// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGHwH02U7aAoYPM7RPiUpaLFP0PZo8URg',
    appId: '1:158243860128:web:07fc896f594e84a2eb23c5',
    messagingSenderId: '158243860128',
    projectId: 'ditonton-af728',
    authDomain: 'ditonton-af728.firebaseapp.com',
    storageBucket: 'ditonton-af728.firebasestorage.app',
    measurementId: 'G-P280XTTK1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9j9u82CprCx7SYBmq-1PifVjMcPPqcm0',
    appId: '1:158243860128:android:b25b0fdbb88c7b65eb23c5',
    messagingSenderId: '158243860128',
    projectId: 'ditonton-af728',
    storageBucket: 'ditonton-af728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYBBOlvH3rIK9GFyfV6FdtHbFL-7AO93M',
    appId: '1:158243860128:ios:e1d212e507117016eb23c5',
    messagingSenderId: '158243860128',
    projectId: 'ditonton-af728',
    storageBucket: 'ditonton-af728.firebasestorage.app',
    iosBundleId: 'com.fandiaspraja.labamu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYBBOlvH3rIK9GFyfV6FdtHbFL-7AO93M',
    appId: '1:158243860128:ios:fda57da85e7da4abeb23c5',
    messagingSenderId: '158243860128',
    projectId: 'ditonton-af728',
    storageBucket: 'ditonton-af728.firebasestorage.app',
    iosBundleId: 'com.example.pmbApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYPf4UjpaFa9e7qoo6mRK3K5t8CsBHFTQ',
    appId: '1:158243860128:web:bb2b3f501350a6a5eb23c5',
    messagingSenderId: '158243860128',
    projectId: 'ditonton-af728',
    authDomain: 'ditonton-af728.firebaseapp.com',
    storageBucket: 'ditonton-af728.firebasestorage.app',
    measurementId: 'G-9WHL3QYTNB',
  );

}